### ISSUE TITLE
HRRR Data Parses into Float32Arrays with Infinity and NaN

### ISSUE THREAD

**Issue by Craytor** [tsupinie/gribjs#1]
When utilizing the package, I have found that HRRR data incorrectly parses. I have tried a few different methods, including the demo for autimnplot-gl and gribjs along with compiling gribjs for use in node. Additionally, I tried using both an inventory file and also creating the files through NCEP's grib filter method. Both "fail" with the same products - by fail, I mean that the Float32Array's were full of Infinity or NaN.

<img width="621" alt="Screenshot 2023-11-23 at 8 49 22 PM" src="https://github.com/tsupinie/gribjs/assets/3680866/e33197cb-1957-4c5f-92e6-cb9cf4300012">

<img width="708" alt="Screenshot 2023-11-23 at 8 49 30 PM" src="https://github.com/tsupinie/gribjs/assets/3680866/1f6284a8-54a4-4d1e-a213-d6ef10f578a2">

For reference, the HRRR data file that I tried loading is: https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20231123/conus/hrrr.t12z.wrfsfcf01.grib2.

I created a simple async for each to go through every product to find which ones were not correctly parsing (producing the array's with Infinity). Here is the output; noting the min, max, first array element.

```
async function run() {
    const url = 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.20231123/conus/hrrr.t12z.wrfsfcf01.grib2';
    const inv = await Grib2Inventory.fromRemote(`${url}.idx`);

    let infinityArr = [];

    await forEachDelay(inv.entries, async invItem => {
        try {
            const g2_file = await inv.search(invItem.inv_string).downloadData(url);
            const data = await g2_file.getMessage(0);
            console.log(data.data)
            if (data.data[0] == Infinity) {
                infinityArr.push(invItem);
            }
            console.log(invItem.inv_string + " | " + data.data.reduce((a, b) => Math.min(a, b)), data.data.reduce((a, b) => Math.max(a, b)), data.data[0]);
        } catch (e) {
            console.log(e)
            console.log("ERROR: " + invItem.inv_string);
        }

    }, 1000)

    console.log(infinityArr);
}
```

```
1:0:d=2023112312:REFC:entire atmosphere:1 hour fcst: | NaN NaN NaN
2:251919:d=2023112312:RETOP:cloud top:1 hour fcst: | -999 8661.16015625 -999
3:351449:d=2023112312:var discipline=0 center=7 local_table=1 parmcat=16 parm=201:entire atmosphere:1 hour fcst: | 0 11.0246000289917 0
4:800641:d=2023112312:VIL:entire atmosphere:1 hour fcst: | 0 6.381279945373535 0
5:1046311:d=2023112312:VIS:surface:1 hour fcst: | 0 0 0
6:2485451:d=2023112312:REFD:1000 m above ground:1 hour fcst: | NaN NaN NaN
7:2610765:d=2023112312:REFD:4000 m above ground:1 hour fcst: | NaN NaN NaN
8:2704683:d=2023112312:REFD:263 K level:1 hour fcst: | NaN NaN NaN
9:2817965:d=2023112312:GUST:surface:1 hour fcst: | NaN NaN Infinity
10:4066576:d=2023112312:UGRD:250 mb:1 hour fcst: | NaN NaN Infinity
11:4739450:d=2023112312:VGRD:250 mb:1 hour fcst: | NaN NaN Infinity
12:5419291:d=2023112312:UGRD:300 mb:1 hour fcst: | NaN NaN Infinity
13:6094032:d=2023112312:VGRD:300 mb:1 hour fcst: | NaN NaN Infinity
14:6764136:d=2023112312:HGT:500 mb:1 hour fcst: | NaN NaN Infinity
15:7441414:d=2023112312:TMP:500 mb:1 hour fcst: | NaN NaN Infinity
16:7981227:d=2023112312:DPT:500 mb:1 hour fcst: | NaN NaN Infinity
17:8755685:d=2023112312:UGRD:500 mb:1 hour fcst: | NaN NaN Infinity
18:9336532:d=2023112312:VGRD:500 mb:1 hour fcst: | NaN NaN Infinity
19:9917085:d=2023112312:HGT:700 mb:1 hour fcst: | NaN NaN Infinity
20:10596587:d=2023112312:TMP:700 mb:1 hour fcst: | NaN NaN Infinity
21:11142778:d=2023112312:DPT:700 mb:1 hour fcst: | NaN NaN Infinity
22:12029339:d=2023112312:DZDT:700 mb:1 hour fcst: | NaN NaN Infinity
23:12892574:d=2023112312:UGRD:700 mb:1 hour fcst: | NaN NaN Infinity
24:13486344:d=2023112312:VGRD:700 mb:1 hour fcst: | NaN NaN Infinity
25:14070223:d=2023112312:HGT:850 mb:1 hour fcst: | NaN NaN Infinity
26:14800991:d=2023112312:TMP:850 mb:1 hour fcst: | NaN NaN Infinity
27:15390333:d=2023112312:DPT:850 mb:1 hour fcst: | NaN NaN Infinity
28:16468921:d=2023112312:UGRD:850 mb:1 hour fcst: | NaN NaN Infinity
29:17092289:d=2023112312:VGRD:850 mb:1 hour fcst: | NaN NaN Infinity
30:17709398:d=2023112312:TMP:925 mb:1 hour fcst: | NaN NaN Infinity
31:18312094:d=2023112312:DPT:925 mb:1 hour fcst: | NaN NaN Infinity
32:19427860:d=2023112312:UGRD:925 mb:1 hour fcst: | NaN NaN Infinity
33:20050967:d=2023112312:VGRD:925 mb:1 hour fcst: | NaN NaN Infinity
34:20668288:d=2023112312:TMP:1000 mb:1 hour fcst: | NaN NaN Infinity
35:21293287:d=2023112312:DPT:1000 mb:1 hour fcst: | NaN NaN Infinity
36:22420311:d=2023112312:UGRD:1000 mb:1 hour fcst: | NaN NaN Infinity
37:23052170:d=2023112312:VGRD:1000 mb:1 hour fcst: | NaN NaN Infinity
38:23675432:d=2023112312:MAXUVV:100-1000 mb above ground:0-1 hour max fcst: | NaN NaN Infinity
39:24234265:d=2023112312:MAXDVV:100-1000 mb above ground:0-1 hour max fcst: | NaN NaN Infinity
40:24850279:d=2023112312:DZDT:0.5-0.8 sigma layer:0-1 hour ave fcst: | NaN NaN Infinity
41:25405891:d=2023112312:MSLMA:mean sea level:1 hour fcst: | 99349 103674 101506
42:26039436:d=2023112312:HGT:1000 mb:1 hour fcst: | NaN NaN Infinity
43:26803440:d=2023112312:MAXREF:1000 m above ground:0-1 hour max fcst: | NaN NaN NaN
44:26975999:d=2023112312:REFD:263 K level:0-1 hour max fcst: | NaN NaN NaN
45:27137271:d=2023112312:MXUPHL:5000-2000 m above ground:0-1 hour max fcst: | 0 5.889999866485596 0
46:27327019:d=2023112312:MNUPHL:5000-2000 m above ground:0-1 hour min fcst: | -2.059999942779541 0 0
47:27531618:d=2023112312:MXUPHL:2000-0 m above ground:0-1 hour max fcst: | 0 2.0999999046325684 0
48:27652455:d=2023112312:MNUPHL:2000-0 m above ground:0-1 hour min fcst: | -1.2400000095367432 0 0
49:27742668:d=2023112312:MXUPHL:3000-0 m above ground:0-1 hour max fcst: | 0 2.6600000858306885 0
50:27873397:d=2023112312:MNUPHL:3000-0 m above ground:0-1 hour min fcst: | -2.069999933242798 0 0
51:27968689:d=2023112312:RELV:2000-0 m above ground:0-1 hour max fcst: | 0 0.003606799989938736 0
52:30064337:d=2023112312:RELV:1000-0 m above ground:0-1 hour max fcst: | 0 0.003606799989938736 0
53:32577972:d=2023112312:HAIL:entire atmosphere:0-1 hour max fcst: | 0 0.027820000424981117 0
54:32706665:d=2023112312:HAIL:0.1 sigma level:0-1 hour max fcst: | 0 0.021379999816417694 0
Simple (un)packing not implemented yet
ERROR: 55:32748665:d=2023112312:HAIL:surface:0-1 hour max fcst:
TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/src/ts/index.ts:180:24)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/test.ts:33:29)
    at Timeout.do_callback (/Users/tyouschak/Code/wxdata/gribjs/test.ts:81:13)
ERROR: 56:32748877:d=2023112312:TCOLG:entire atmosphere (considered as a single layer):0-1 hour max fcst:
Simple (un)packing not implemented yet
ERROR: 57:32783910:d=2023112312:LTNGSD:1 m above ground:1 hour fcst:
58:32784098:d=2023112312:LTNGSD:2 m above ground:1 hour fcst: | 0 2.193000078201294 0
Simple (un)packing not implemented yet
ERROR: 59:32814921:d=2023112312:LTNG:entire atmosphere:1 hour fcst:
60:32815109:d=2023112312:UGRD:80 m above ground:1 hour fcst: | NaN NaN Infinity
61:33956845:d=2023112312:VGRD:80 m above ground:1 hour fcst: | NaN NaN Infinity
62:35113970:d=2023112312:PRES:surface:1 hour fcst: | 0 0 0
63:36623708:d=2023112312:HGT:surface:1 hour fcst: | NaN NaN Infinity
64:38777403:d=2023112312:TMP:surface:1 hour fcst: | NaN NaN Infinity
65:40104425:d=2023112312:ASNOW:surface:0-1 hour acc fcst: | 0 0.09357199817895889 0
66:40263498:d=2023112312:MSTAV:0 m underground:1 hour fcst: | 0 100 100
67:41726267:d=2023112312:CNWAT:surface:1 hour fcst: | 0 0.5 0
68:41858697:d=2023112312:WEASD:surface:1 hour fcst: | NaN NaN NaN
69:42149565:d=2023112312:SNOWC:surface:1 hour fcst: | 0 100 0
70:42365529:d=2023112312:SNOD:surface:1 hour fcst: | 0 32.382999420166016 0
71:42578538:d=2023112312:TMP:2 m above ground:1 hour fcst: | NaN NaN Infinity
72:43801379:d=2023112312:POT:2 m above ground:1 hour fcst: | NaN NaN Infinity
73:45003363:d=2023112312:SPFH:2 m above ground:1 hour fcst: | 0.0004900000058114529 0.01800999976694584 0.010180000215768814
74:46369186:d=2023112312:DPT:2 m above ground:1 hour fcst: | NaN NaN Infinity
75:47563491:d=2023112312:RH:2 m above ground:1 hour fcst: | 6.400000095367432 100 65.5999984741211
76:49166049:d=2023112312:MASSDEN:8 m above ground:1 hour fcst: | 1.0310667178437657e-25 7.601119733635642e-8 9.920000237917392e-11
Simple (un)packing not implemented yet
ERROR: 77:50286921:d=2023112312:UGRD:10 m above ground:1 hour fcst:
Simple (un)packing not implemented yet
ERROR: 78:52668536:d=2023112312:VGRD:10 m above ground:1 hour fcst:
79:54812008:d=2023112312:WIND:10 m above ground:0-1 hour max fcst: | NaN NaN Infinity
80:56069495:d=2023112312:MAXUW:10 m above ground:0-1 hour max fcst: | NaN NaN Infinity
81:57420146:d=2023112312:MAXVW:10 m above ground:0-1 hour max fcst: | NaN NaN Infinity
82:58751693:d=2023112312:CPOFP:surface:1 hour fcst: | NaN NaN NaN
83:58811455:d=2023112312:PRATE:surface:1 hour fcst: | 0 0.015200000256299973 0
84:58839627:d=2023112312:APCP:surface:0-1 hour acc fcst: | 0 14.810999870300293 0
85:59065243:d=2023112312:WEASD:surface:0-1 hour acc fcst: | 0 4.199399948120117 0
86:59229502:d=2023112312:FROZR:surface:0-1 hour acc fcst: | 0 0.6867679953575134 0
87:59286202:d=2023112312:FRZR:surface:0-1 hour acc fcst: | 0 1.8167999982833862 0
88:59416994:d=2023112312:SSRUN:surface:0-1 hour acc fcst: | NaN NaN NaN
89:59417328:d=2023112312:BGRUN:surface:0-1 hour acc fcst: | NaN NaN NaN
90:59417596:d=2023112312:CSNOW:surface:1 hour fcst: | 0 1 0
91:59447049:d=2023112312:CICEP:surface:1 hour fcst: | 0 1 0
92:59447444:d=2023112312:CFRZR:surface:1 hour fcst: | 0 1 0
93:59451343:d=2023112312:CRAIN:surface:1 hour fcst: | 0 1 0
94:59475296:d=2023112312:SFCR:surface:1 hour fcst: | 0 0.800000011920929 0
95:61401250:d=2023112312:FRICV:surface:1 hour fcst: | 0 2.0899999141693115 0.14000000059604645
96:62556576:d=2023112312:SHTFL:surface:1 hour fcst: | -284 534 9
97:63829258:d=2023112312:LHTFL:surface:1 hour fcst: | -48 636 125
98:64892150:d=2023112312:VEG:surface:1 hour fcst: | 0 95.0999984741211 0
99:66334003:d=2023112312:var discipline=2 center=7 local_table=1 parmcat=0 parm=231:surface:1 hour fcst: | 0 74.0999984741211 0
100:67450140:d=2023112312:var discipline=2 center=7 local_table=1 parmcat=0 parm=232:surface:1 hour fcst: | 0 100 0
101:68327074:d=2023112312:LAI:surface:1 hour fcst: | NaN NaN NaN
102:69030370:d=2023112312:GFLUX:surface:1 hour fcst: | 0 0 0
103:69646467:d=2023112312:VGTYP:surface:1 hour fcst: | 1 19 17
104:70427651:d=2023112312:LFTX:500-1000 mb:1 hour fcst: | -4.400000095367432 34.400001525878906 9.800000190734863
105:71417570:d=2023112312:CAPE:surface:1 hour fcst: | 0 0 0
106:71583269:d=2023112312:CIN:surface:1 hour fcst: | -514 0 0
TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/src/ts/index.ts:180:24)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/test.ts:33:29)
    at Timeout.do_callback (/Users/tyouschak/Code/wxdata/gribjs/test.ts:81:13)
ERROR: 107:71806495:d=2023112312:PWAT:entire atmosphere (considered as a single layer):1 hour fcst:
TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/src/ts/index.ts:180:24)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/test.ts:33:29)
    at Timeout.do_callback (/Users/tyouschak/Code/wxdata/gribjs/test.ts:81:13)
ERROR: 108:72615862:d=2023112312:AOTK:entire atmosphere (considered as a single layer):1 hour fcst:
TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/src/ts/index.ts:180:24)
    at <anonymous> (/Users/tyouschak/Code/wxdata/gribjs/test.ts:33:29)
    at Timeout.do_callback (/Users/tyouschak/Code/wxdata/gribjs/test.ts:81:13)
ERROR: 109:73708874:d=2023112312:COLMD:entire atmosphere (considered as a single layer):1 hour fcst:
110:75016513:d=2023112312:TCOLW:entire atmosphere:1 hour fcst: | 0 3.1273999214172363 0.03700000047683716
111:76236026:d=2023112312:TCOLI:entire atmosphere:1 hour fcst: | 0 0.3028639853000641 0
112:77442544:d=2023112312:TCDC:boundary layer cloud layer:1 hour fcst: | 0 100 45
113:78188988:d=2023112312:LCDC:low cloud layer:1 hour fcst: | 0 100 45
114:79014855:d=2023112312:MCDC:middle cloud layer:1 hour fcst: | 0 100 0
115:79244673:d=2023112312:HCDC:high cloud layer:1 hour fcst: | 0 100 0
116:79567843:d=2023112312:TCDC:entire atmosphere:1 hour fcst: | 0 100 45
117:80358590:d=2023112312:HGT:cloud ceiling:1 hour fcst: | NaN NaN Infinity
Simple (un)packing not implemented yet
ERROR: 118:81552161:d=2023112312:HGT:cloud base:1 hour fcst:
119:83856856:d=2023112312:PRES:cloud base:1 hour fcst: | 0 0 0
120:84918265:d=2023112312:PRES:cloud top:1 hour fcst: | 0 0 0
121:85535665:d=2023112312:HGT:cloud top:1 hour fcst: | NaN NaN Infinity
122:86633343:d=2023112312:ULWRF:top of atmosphere:1 hour fcst: | 129.89999389648438 305.70001220703125 292.5
123:88413535:d=2023112312:DSWRF:surface:1 hour fcst: | 0 384.8999938964844 0
124:89184422:d=2023112312:DLWRF:surface:1 hour fcst: | 135 444.29998779296875 355.20001220703125
125:91213096:d=2023112312:USWRF:surface:1 hour fcst: | NaN NaN NaN
126:91764780:d=2023112312:ULWRF:surface:1 hour fcst: | NaN NaN Infinity
127:93411984:d=2023112312:CFNSF:surface:1 hour fcst: | 0 168.3000030517578 0
128:93416435:d=2023112312:VBDSF:surface:1 hour fcst: | 0 870.9000244140625 0
129:94219243:d=2023112312:VDDSF:surface:1 hour fcst: | 0 218.60000610351562 0
130:94992663:d=2023112312:USWRF:top of atmosphere:1 hour fcst: | 0 314.70001220703125 0
131:95749471:d=2023112312:HLCY:3000-0 m above ground:1 hour fcst: | -176.39999389648438 733.2000122070312 17.700000762939453
132:97672970:d=2023112312:HLCY:1000-0 m above ground:1 hour fcst: | -222.1999969482422 385.6000061035156 -2.5999999046325684
133:99556467:d=2023112312:USTM:0-6000 m above ground:1 hour fcst: | NaN NaN Infinity
134:100546004:d=2023112312:VSTM:0-6000 m above ground:1 hour fcst: | NaN NaN Infinity
Simple (un)packing not implemented yet
ERROR: 135:101470386:d=2023112312:VUCSH:0-1000 m above ground:1 hour fcst:
Simple (un)packing not implemented yet
ERROR: 136:103852001:d=2023112312:VVCSH:0-1000 m above ground:1 hour fcst:
Simple (un)packing not implemented yet
ERROR: 137:106233616:d=2023112312:VUCSH:0-6000 m above ground:1 hour fcst:
Simple (un)packing not implemented yet
ERROR: 138:108615231:d=2023112312:VVCSH:0-6000 m above ground:1 hour fcst:
139:111234988:d=2023112312:HGT:0C isotherm:1 hour fcst: | 0 5348.47998046875 4985.919921875
140:113218190:d=2023112312:RH:0C isotherm:1 hour fcst: | 1 100 2
141:114055882:d=2023112312:PRES:0C isotherm:1 hour fcst: | 0 0 0
142:115056254:d=2023112312:HGT:highest tropospheric freezing level:1 hour fcst: | 0 0 0
143:115800711:d=2023112312:RH:highest tropospheric freezing level:1 hour fcst: | 1 100 2
144:116492444:d=2023112312:PRES:highest tropospheric freezing level:1 hour fcst: | 0 0 0
145:117306220:d=2023112312:HGT:263 K level:1 hour fcst: | 0 0 0
146:117982449:d=2023112312:HGT:253 K level:1 hour fcst: | 0 0 0
147:118609163:d=2023112312:4LFTX:180-0 mb above ground:1 hour fcst: | -4.099999904632568 25.700000762939453 10.199999809265137
148:119575121:d=2023112312:CAPE:180-0 mb above ground:1 hour fcst: | 0 0 0
149:119723122:d=2023112312:CIN:180-0 mb above ground:1 hour fcst: | -503 0 -1
150:119898507:d=2023112312:HPBL:surface:1 hour fcst: | NaN NaN Infinity
151:122707239:d=2023112312:HGT:level of adiabatic condensation from sfc:1 hour fcst: | NaN NaN Infinity
152:125563654:d=2023112312:CAPE:90-0 mb above ground:1 hour fcst: | 0 0 0
153:125677869:d=2023112312:CIN:90-0 mb above ground:1 hour fcst: | -494 0 -3
154:125873170:d=2023112312:CAPE:255-0 mb above ground:1 hour fcst: | 0 0 0
155:125987059:d=2023112312:CIN:255-0 mb above ground:1 hour fcst: | -514 0 0
156:126116471:d=2023112312:HGT:equilibrium level:1 hour fcst: | NaN NaN Infinity
157:127911700:d=2023112312:PLPL:255-0 mb above ground:1 hour fcst: | 0 0 0
158:128846339:d=2023112312:CAPE:0-3000 m above ground:1 hour fcst: | 0 179.8000030517578 3.0999999046325684
159:129340875:d=2023112312:HGT:level of free convection:1 hour fcst: | 339.8910827636719 9221.0107421875 1232.5311279296875
160:131941790:d=2023112312:var discipline=0 center=7 local_table=1 parmcat=7 parm=204:surface:1 hour fcst: | -75 343 -0.4000000059604645
161:132437004:d=2023112312:var discipline=0 center=7 local_table=1 parmcat=7 parm=206:0-500 m above ground:1 hour fcst: | 0 180 120.5999984741211
162:134550301:d=2023112312:LAYTH:261 K level - 256 K level:1 hour fcst: | 0 4491 575
163:135901695:d=2023112312:var discipline=0 center=7 local_table=1 parmcat=7 parm=205:0-3000 m above ground:1 hour fcst: | 0 34.459999084472656 0
164:136285495:d=2023112312:RHPW:entire atmosphere:1 hour fcst: | 5.300000190734863 97.5 21.799999237060547
165:137372306:d=2023112312:LAND:surface:1 hour fcst: | 0 1 0
166:137422782:d=2023112312:ICEC:surface:1 hour fcst: | 0 1 0
167:137425250:d=2023112312:SBT123:top of atmosphere:1 hour fcst: | 212.9600067138672 257.1099853515625 247.41000366210938
168:138761428:d=2023112312:SBT124:top of atmosphere:1 hour fcst: | 213.80999755859375 298.7099914550781 291.7200012207031
169:141018379:d=2023112312:SBT113:top of atmosphere:1 hour fcst: | 212 255.19000244140625 250.22999572753906
170:142245974:d=2023112312:SBT114:top of atmosphere:1 hour fcst: | 212.72000122070312 296.92999267578125 293.3500061035156
```

Have you noticed any issues when parsing HRRR?

**Comment by tsupinie** [comment]
I wasn't planning on fixing this this evening, but turns out it was fairly easy. I've put the fix in a [branch](https://github.com/tsupinie/gribjs/tree/signed-scale-factor). Let me know when you get a chance to test it.

**Comment by Craytor** [comment]
I just went and tested the update on that branch and it is now parsing the data correctly for each product.
